name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build bottle
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # NOTE: clean install Homebrew, It fixes /usr permissions.
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - run: brew tap sasaplus1/kaoriya-vim
      - run: brew install --build-bottle --debug --verbose kaoriya-vim
      - run: brew bottle --debug --verbose kaoriya-vim
      - id: bottle
        run: echo "::set-output name=name::$(ls -1 kaoriya-vim--*.bottle.tar.gz)"
      - run: shasum -a 256 -b "${{ steps.bottle.outputs.name }}" > "${{ steps.bottle.outputs.name }}"-sha256sum.txt
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.bottle.outputs.name }}
          path: ${{ steps.bottle.outputs.name }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.bottle.outputs.name }}-sha256sum.txt
          path: ${{ steps.bottle.outputs.name }}-sha256sum.txt
