name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build bottle
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # NOTE: clean install Homebrew, It fixes /usr permissions.
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - run: brew tap sasaplus1/kaoriya-vim
      - run: brew install --build-bottle --debug --verbose kaoriya-vim
      - run: brew bottle --debug --verbose kaoriya-vim
      - id: bottle
        run: echo "::set-output name=name::$(ls -1 kaoriya-vim--*.bottle.tar.gz)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.bottle.outputs.name }}
          path: ${{ steps.bottle.outputs.name }}
  release:
    name: release bottles
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: find artifacts -type f -print0 | xargs -0 mv -t .
      - run: rm -rf artifacts
      - run: ls -l
      - run: shasum -a 256 -b *.tar.gz | tee sha256sum.txt
      - run: file --mime-type *.tar.gz sha256sum.txt
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: text/plain
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kaoriya-vim--8.2.0087.catalina.bottle.tar.gz
          asset_name: kaoriya-vim--8.2.0087.catalina.bottle.tar.gz
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kaoriya-vim--8.2.0087.x86_64_linux.bottle.tar.gz
          asset_name: kaoriya-vim--8.2.0087.x86_64_linux.bottle.tar.gz
          asset_content_type: application/gzip
