name: test

on:
  - push
  - pull_request

jobs:
  audit:
    name: audit formula
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /usr/local/Homebrew/Library/Homebrew/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: brew audit --strict ./kaoriya-vim.rb
