name: test

on:
  push:
  pull_request:
  schedule:
    # NOTE: at AM8:45 every monday by JST
    - cron: '45 23 * * 1'

jobs:
  test-bot:
    name: test with test-bot
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew test-bot --verbose ./kaoriya-vim.rb
